/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho1;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanadis
 */
public class Transferencia extends javax.swing.JFrame {

    /**
     * Creates new form Transferencia
     */
    Gerenciador gerenciador;

    public Transferencia(Gerenciador ger) {
        this.gerenciador = ger;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelar = new javax.swing.JButton();
        continuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numero1 = new javax.swing.JTextField();
        numero2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });

        jLabel1.setText("Transferência");

        jLabel2.setText("Remetente: ");

        jLabel3.setText("Destinatario: ");

        jLabel4.setText("Valor:");

        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(numero1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero2)
                            .addComponent(valor))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(continuar)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(continuar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
        this.gerenciador.abrirTelaOperacoes();
    }//GEN-LAST:event_cancelarActionPerformed

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        int numero1 = Integer.parseInt(this.numero1.getText());
        int numero2 = Integer.parseInt(this.numero2.getText());
        String nome1 = "";
        String nome2 = "";
        int conta1 = 0;
        int conta2 = 0;
        int sucesso = 0;
        double valor = Double.parseDouble(this.valor.getText());

        if (numero1 == this.gerenciador.comum.getNumero()) {
            nome1 = this.gerenciador.comum.getNome();
            conta1 = 1;
        } else if (numero1 == this.gerenciador.poupanca.getNumero()) {
            nome1 = this.gerenciador.poupanca.getNome();
            conta1 = 2;
        } else if (numero1 == this.gerenciador.especial.getNumero()) {
            nome1 = this.gerenciador.especial.getNome();
            conta1 = 3;
        }
        if (numero2 == this.gerenciador.comum.getNumero()) {
            nome2 = this.gerenciador.comum.getNome();
            conta2 = 1;
        } else if (numero2 == this.gerenciador.poupanca.getNumero()) {
            nome2 = this.gerenciador.poupanca.getNome();
            conta2 = 2;
        } else if (numero2 == this.gerenciador.especial.getNumero()) {
            nome2 = this.gerenciador.especial.getNome();
            conta2 = 3;
        }

        JFrame confirmar = new JFrame();
        int resposta = JOptionPane.showConfirmDialog(confirmar, "Confirmar operação? Remetente: " + nome1 + "; destinatario: " + nome2, "", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            switch (conta1) {
                case 1:
                    sucesso = this.gerenciador.comum.sacar(valor);
                    if (sucesso == 1) {
                        switch (conta2) {
                            case 2:
                                this.gerenciador.poupanca.depositar(valor);
                                this.gerenciador.armazenar(this.gerenciador.poupanca);
                                break;
                            case 3:
                                this.gerenciador.especial.depositar(valor);
                                this.gerenciador.armazenar(this.gerenciador.especial);
                                break;
                        }
                        this.gerenciador.armazenar(this.gerenciador.comum);
                    }
                    break;
                case 2:
                    sucesso = this.gerenciador.poupanca.sacar(valor);
                    if (sucesso == 1) {
                        switch (conta2) {
                            case 1:
                                this.gerenciador.comum.depositar(valor);
                                this.gerenciador.armazenar(this.gerenciador.comum);
                                break;
                            case 3:
                                this.gerenciador.especial.depositar(valor);
                                this.gerenciador.armazenar(this.gerenciador.especial);
                                break;
                        }
                        this.gerenciador.armazenar(this.gerenciador.poupanca);
                    }

                    break;
                case 3:
                    sucesso = this.gerenciador.especial.sacar(valor);
                    if (sucesso == 1 || sucesso == 3) {
                        switch (conta2) {
                            case 1:
                                this.gerenciador.comum.depositar(valor);
                                this.gerenciador.armazenar(this.gerenciador.comum);
                                break;
                            case 2:
                                this.gerenciador.poupanca.depositar(valor);
                                this.gerenciador.armazenar(this.gerenciador.poupanca);
                                break;
                        }
                        this.gerenciador.armazenar(this.gerenciador.especial);
                    }
                    break;
            }
            if (sucesso == 1 || sucesso == 3) {
                JOptionPane.showMessageDialog(null, "Transferência efetuada com sucesso");
                this.gerenciador.abrirTelaOperacoes();
            } else {
                JOptionPane.showMessageDialog(null, "Operação não realizada, saldo insuficiente");
                this.gerenciador.abrirTelaOperacoes();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Transferência cancelada");
            this.gerenciador.abrirTelaOperacoes();
        }
        confirmar.dispose();
        this.dispose();
    }//GEN-LAST:event_continuarActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencia(new Gerenciador()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton continuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
